steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg HF_TOKEN=$$HF_TOKEN \
          -t $_IMAGE_NAME \
          .
    secretEnv: ['HF_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pawfect-edit-inpaint'
      - '--image=$_IMAGE_NAME'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--gpu=1'
      - '--gpu-type=nvidia-l4'
      - '--no-gpu-zonal-redundancy'
      - '--cpu=4'
      - '--memory=16Gi'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--concurrency=1'
      - '--timeout=300'
      - '--set-secrets=FIREBASE_CREDENTIALS=FIREBASE_CREDENTIALS:latest,HF_TOKEN=HF_TOKEN:latest'
      - '--startup-probe=httpGet.path=/health,initialDelaySeconds=30,periodSeconds=10,failureThreshold=24,timeoutSeconds=5'
      - '--liveness-probe=httpGet.path=/health'

availableSecrets:
  secretManager:
    - versionName: projects/pawfect-edit/secrets/HF_TOKEN/versions/latest
      env: 'HF_TOKEN'

substitutions:
  _IMAGE_NAME: 'gcr.io/pawfect-edit/pawfect-edit-inpaint'
  _REGION: 'us-east4'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
